[package]
name = "tari_exchange"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more.workspace = true
tari_template_lib.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1"
